name: Run Gosec
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Get Diff
        uses: technote-space/get-diff-action@v6.1.0
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
      - name: Run Gosec Security Scanner
        uses: cosmos/gosec@master
        with:
          # we let the report trigger content trigger a failure using the GitHub Security features.
          args: '-no-fail -fmt txt -out results.txt ./...'
        if: "env.GIT_DIFF_FILTERED != ''"
      - uses: actions/upload-artifact@v3
        with:
          name: gosec-report.txt
          path: results.txt
        if: "env.GIT_DIFF_FILTERED != ''"
